# Generated by Django 5.2.3 on 2025-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_quizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='pdf_link',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
