# Generated by Django 5.2.3 on 2025-06-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_remove_quizresult_pdf_link_quizresult_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf_results/'),
        ),
    ]
