# Generated by Django 5.2.3 on 2025-06-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_alter_quizresult_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
