# Generated by Django 5.2.3 on 2025-06-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_alter_quizresult_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
