# Generated by Django 5.2.3 on 2025-06-19 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_quizresult_end_time_quizresult_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz_app.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Choice Text'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quizset', verbose_name='Quiz Set'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_app.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='PDF File'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quizset', verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='status',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], default='Fail', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='time_taken',
            field=models.DurationField(verbose_name='Time Taken'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total_questions',
            field=models.IntegerField(verbose_name='Total Questions'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='quizset',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='quizset',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Quiz Title'),
        ),
    ]
