# Generated by Django 5.2.3 on 2025-06-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_question_question_type_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
    ]
