# Generated by Django 5.2.3 on 2025-06-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0010_useranswer_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='is_correct',
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pass', 'Pass'), ('Fail', 'Fail')], default='Pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='time_taken',
            field=models.DurationField(blank=True, null=True, verbose_name='Time Taken'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total_questions',
            field=models.IntegerField(default=0, verbose_name='Total Questions'),
        ),
    ]
