# Generated by Django 5.2.3 on 2025-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0012_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='grade',
            field=models.FloatField(blank=True, null=True, verbose_name='Grade (0-100)'),
        ),
    ]
