# Generated by Django 5.2.3 on 2025-06-30 07:58

import quiz_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0016_alter_choice_question_alter_question_quiz_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='image_name',
            field=models.CharField(blank=True, choices=quiz_app.models.get_quiz_images, max_length=255, null=True, verbose_name='Optional Image'),
        ),
    ]
